apiVersion: v1
kind: Service
metadata:
  name: nginxer-service
  labels:
    app: nginxer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginxer